language: node_js
sudo: false
env:
  - NODE_ENV='production'
node_js:
  - "stable"
before_install:
  - npm update -q
install:
  - npm install -g codecov
script:
  - npm run report-coverage
  - codecov
