language: node_js
sudo: false
env:
  - NODE_ENV='production'
node_js:
  - "stable"
before_install:
  - export PATH=\`echo ${PATH} | sed -re 's,(^|:)(./)?node_modules/.bin($|:),\1,'\`
install:
  - npm install -g codecov
script:
  - npm run report-coverage
  - codecov
